[build]
  command = "npm run build"
  publish = "dist/NTG-Website/browser"

[[redirects]]
  from = "/api/*"
  to = "https://ntgwebsitebackend.onrender.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

