[build]
  command = "npm run build"
  publish = "dist/NTG-Website/browser"

# Proxy API calls to Render
[[redirects]]
  from = "/api/*"
  to = "https://ntgwebsitebackend.onrender.com/api/:splat"
  status = 200
  force = true

# SPA fallback (keep last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
